Repository PDA-coworKing/coworKingSpace, pull requests merged in 2024-04, with the labels that each got.

#2 #1 feat: 디폴트 스타일 적용 및 hear section 제목 구현
  index.html
  styles/desktop.css
Labels: ✨ feature, 💄 design

#3 #1 design: 카드 스타일 구현
  .gitignore
  assets/Alex-Nguyen.svg
  assets/David-Wilson.svg
  assets/Liam-Brown.svg
  assets/Michael-Rodriguez.svg
  assets/Michael-Thompson.svg
  index.html
  styles/desktop.css
Labels: ✨ feature, 💄 design

#8 #6 style: 공통 적용 css common.css 파일로 분리
  styles/common.css
  styles/desktop.css
Labels: ✨ style

#10 #6 fix: index.html에 common.css 외부 스타일시트 적용
  index.html
Labels: 🐛 fix

#11 #6 design: roadmap section 레이아웃 구조 생성 및 디자인 구현
  assets/CaretCircleDown.svg
  assets/toggleOpen.svg
  index.html
  styles/common.css
  styles/roadmap.css
Labels: ✨ feature, 💄 design

#14 #6 feat: roadmap section 토글 오픈 애니메이션 구현
  index.html
  styles/roadmap.css
Labels: ✨ feature

#17 #9 feat: header 데스크탑뷰 만들기
  assets/Logoipsum1.svg
  assets/Logoipsum2.svg
  assets/Logoipsum3.svg
  assets/Logoipsum4.svg
  assets/Logoipsum5.svg
  assets/Placeholder-Img.svg
  assets/TitleCircle.svg
  index.html
  src/header.html
  styles/header.css
Labels: ✨ feature, 💄 design

#16 #15 feat: seize section 데스크탑 뷰 구현
  assets/seizeImage.svg
  src/seize.html
  styles/seize.css
Labels: ✨ feature, 💄 design

#23 #18 feat: insights section 데스크탑 뷰 구현
  assets/insightTitleImg.svg
  assets/productivity.svg
  assets/readmoreVector.svg
  assets/talk.svg
  assets/trending.svg
  index.html
  src/insights.html
  styles/insights.css
Labels: ✨ feature, 💄 design

#27 #21 fix: 비디오 스타일 적용을 위한 레이아웃 구조 변경
  src/explore.html
Labels: 🐛 fix

#28 #24 feat: footer 데스크탑 뷰 구현
  assets/cowork.svg
  index.html
  src/footer.html
  styles/footer.css
Labels: ✨ feature, 💄 design
